version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: bdpruebatecnica
    ports:
      - "5436:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ../Base de datos/bd.sql:/docker-entrypoint-initdb.d/bd.sql
volumes:
  postgres_data:
